name: Deploy to Dreamhost

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via Rsync
        env:
          SSHPASS: ${{ secrets.DREAMHOST_PASSWORD }}
        run: |
          sshpass -e rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./web/ ${{ secrets.DREAMHOST_USERNAME }}@${{ secrets.DREAMHOST_SERVER }}:/home/${{ secrets.DREAMHOST_USERNAME }}/lawfulstay.com/
