name: Deploy to Dreamhost

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'web/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SFTP Deploy to Dreamhost
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.DREAMHOST_USERNAME }}
          server: ${{ secrets.DREAMHOST_SERVER }}
          port: 22
          password: ${{ secrets.DREAMHOST_PASSWORD }}
          local_path: './web/*'
          remote_path: '/home/${{ secrets.DREAMHOST_USERNAME }}/lawfulstay.com/'
          sftp_only: true
